CREATE DATABASE wallet_management_system;

USE DATABASE wallet_management_system;

CREATE TABLE Wallets (
  id VARCHAR(36) PRIMARY KEY,
  balance DECIMAL(20, 4) NOT NULL,
  name VARCHAR(255) NOT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Transactions (
  id VARCHAR(36) PRIMARY KEY,
  walletId VARCHAR(36),
  amount DECIMAL(20, 4) NOT NULL,
  balance DECIMAL(20, 4) NOT NULL,
  description VARCHAR(255) NOT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  type ENUM('CREDIT', 'DEBIT') NOT NULL,
  FOREIGN KEY (walletId) REFERENCES Wallets(id)
);
